version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: echo_server
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: echo_client
    environment:
      - SERVER_URL=http://server:8000
    depends_on:
      - server
