version: "3.8"

services:
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: master3
    environment:
      - SECONDARIES=http://secondary1:8001,http://secondary2:8001
      - MAX_RETRIES=5
      - INITIAL_BACKOFF=1.0
      - BACKOFF_MULTIPLIER=2.0
    ports:
      - "8000:8000"
    depends_on:
      - secondary1
      - secondary2

  secondary1:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    container_name: secondary1_3
    environment:
      - SECONDARY_ID=sec1
      - REPLICATION_DELAY=2
    ports:
      - "8001:8001"

  secondary2:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    container_name: secondary2_3
    environment:
      - SECONDARY_ID=sec2
      - REPLICATION_DELAY=2
    ports:
      - "8002:8001"
